import { Router } from 'express';
import { z } from 'zod';
import { Category, Transaction, Trip } from '../models/index.js';
import { ApiError, asyncHandler, ok } from '../utils/index.js';
const router = Router();
const schema = z.object({ type: z.enum(['income', 'expense', 'saving']), amount: z.number().int().positive(), categoryId: z.string().min(1), date: z.coerce.date(), note: z.string().max(240).optional(), paymentMethod: z.enum(['cash', 'card', 'bank', 'mobile-banking']).optional(), tripId: z.string().nullable().optional() });
async function validated(body, userId, partial = false) { const parsed = (partial ? schema.partial() : schema).safeParse(body); if (!parsed.success) throw new ApiError(422, 'Validation failed', parsed.error.flatten().fieldErrors); if (parsed.data.categoryId && !(await Category.exists({ _id: parsed.data.categoryId, userId }))) throw new ApiError(422, 'Invalid category'); if (parsed.data.tripId && !(await Trip.exists({ _id: parsed.data.tripId, userId }))) throw new ApiError(422, 'Invalid trip'); return parsed.data; }
router.get('/', asyncHandler(async (req, res) => { const page = Math.max(1, +(req.query.page || 1)), limit = Math.min(100, Math.max(1, +(req.query.limit || 20))); const q = { userId: req.user._id }; for (const key of ['type', 'categoryId', 'tripId']) if (req.query[key]) q[key] = req.query[key]; if (req.query.from || req.query.to) q.date = { ...(req.query.from && { $gte: new Date(req.query.from) }), ...(req.query.to && { $lte: new Date(req.query.to) }) }; if (req.query.search) q.note = { $regex: String(req.query.search).replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), $options: 'i' }; if (req.query.min || req.query.max) q.amount = { ...(req.query.min && { $gte: +req.query.min }), ...(req.query.max && { $lte: +req.query.max }) }; const [items, total] = await Promise.all([Transaction.find(q).populate('categoryId', 'name color icon').populate('tripId', 'title').sort({ date: req.query.sort === 'oldest' ? 1 : -1 }).skip((page - 1) * limit).limit(limit), Transaction.countDocuments(q)]); ok(res, { items, pagination: { page, limit, total, pages: Math.ceil(total / limit) } }); }));
router.post('/', asyncHandler(async (req, res) => { const data = await validated(req.body, req.user._id); ok(res, await Transaction.create({ ...data, userId: req.user._id }), 'Transaction created successfully', 201); }));
router.get('/:id', asyncHandler(async (req, res) => { const item = await Transaction.findOne({ _id: req.params.id, userId: req.user._id }).populate('categoryId').populate('tripId'); if (!item) throw new ApiError(404, 'Transaction not found'); ok(res, item); }));
router.patch('/:id', asyncHandler(async (req, res) => { const data = await validated(req.body, req.user._id, true); const item = await Transaction.findOneAndUpdate({ _id: req.params.id, userId: req.user._id }, data, { new: true, runValidators: true }); if (!item) throw new ApiError(404, 'Transaction not found'); ok(res, item, 'Transaction updated'); }));
router.delete('/:id', asyncHandler(async (req, res) => { const item = await Transaction.findOneAndDelete({ _id: req.params.id, userId: req.user._id }); if (!item) throw new ApiError(404, 'Transaction not found'); ok(res, item, 'Transaction deleted'); }));
export default router;
